---
AllCops:
  Exclude:
    - db/schema.rb

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Rails/Output:
  Exclude:
    - db/seeds.rb

Rails/TimeZone:
  Exclude:
    - config/dev_unicorn.rb
