default: &default
  adapter: mysql2
  username: ide_app
  password: password
  host: 127.0.0.1
  pool: 5
  # TODO: Enable this as soon as aaf-lipstick is updated to support it.
  # encoding: utf8
  # collation: utf8_bin

development:
  <<: *default
  database: ide_development

test:
  <<: *default
  database: ide_test

production:
  <<: *default
  username: <%= ENV['IDE_DB_USERNAME'] %>
  password: <%= ENV['IDE_DB_PASSWORD'] %>
  database: <%= ENV['IDE_DB_NAME'] %>
  host: <%= ENV['IDE_DB_HOST'] %>
  port: <%= ENV['IDE_DB_PORT'] %>
